[package]
name = "mcpack-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
serde = "1.0.227"
serde_derive = "1.0.227"
serde_json = "1.0.145"
toml = "0.9.7"
